# Generated by Django 4.2.7 on 2024-01-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0004_alter_picture_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='job_profile',
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
