# Generated by Django 4.2.7 on 2024-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0006_alter_picture_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
