# Generated by Django 4.2.7 on 2024-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0009_alter_picture_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_profile', models.CharField(max_length=1000)),
                ('about_project', models.TextField()),
                ('project_file', models.FileField(default=None, upload_to='project/')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
