# Generated by Django 4.2.7 on 2024-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0010_project_delete_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='about_project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
