# Generated by Django 4.2.7 on 2024-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0011_remove_project_about_project_project_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(default=None, upload_to='photo/'),
        ),
    ]
