# Generated by Django 4.2.7 on 2024-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0012_alter_project_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about_project',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(default=None, null=True, upload_to='photo/'),
        ),
    ]
