# Generated by Django 4.2.7 on 2024-03-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0013_project_about_project_alter_project_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_photo',
        ),
        migrations.AddField(
            model_name='project',
            name='project_icon',
            field=models.ImageField(default=None, max_length=333, null=True, upload_to='images/'),
        ),
    ]
