# Generated by Django 4.2.7 on 2024-03-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0014_remove_project_project_photo_project_project_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_profile', models.CharField(max_length=1000)),
                ('about', models.TextField()),
                ('photo', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_profile', models.CharField(max_length=1000)),
                ('about_project', models.TextField()),
                ('project_photo', models.ImageField(default=None, upload_to='images/')),
                ('project_file', models.FileField(default=None, upload_to='project/')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
