# Generated by Django 4.2.7 on 2024-03-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0015_p_projects_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_photo',
        ),
    ]
