# Generated by Django 4.2.7 on 2024-03-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servise', '0016_delete_p_remove_projects_project_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
